/// UI string tables for the two supported app languages. Keys are shared;
/// each locale has a matching entry. Add new keys to BOTH maps together —
/// AppLocale.t() falls back to English if a key is missing from Arabic,
/// but that should only ever happen mid-edit, not in a committed state.
class AppStrings {
  AppStrings._();

  static const Map<String, String> en = {
    // Bottom nav (main_shell.dart)
    'nav_home': 'Home',
    'nav_journey': 'Journey',
    'nav_hunt': 'Hunt',
    'nav_talk': 'Talk',
    'nav_profile': 'Profile',

    // Home screen
    'home_greeting': 'Good Morning',
    'home_headline': "Discover Jordan's Hidden Stories",
    'home_plan_journey': 'Plan a Journey',
    'home_hikaya_hunt': 'Hikaya Hunt',
    'home_hikaya_talk': 'Hikaya Talk',
    'home_continue_journey': 'Continue Your Journey',
    'home_continue_button': 'Continue',
    'home_popular_destinations': 'Popular Destinations',
    'home_view_all': 'View All',
    'home_no_destinations': 'No destinations yet — run /seed',
    'home_load_error': "Couldn't load destinations",
    'unit_stops': 'stops',
    'unit_hours': 'hours',

    // Profile screen
    'profile_title': 'Profile',
    'profile_not_logged_in': 'Not logged in',
    'profile_coins': 'Coins',
    'profile_badges': 'Badges',
    'profile_visited': 'Visited',
    'profile_view_all_badges': 'View All Badges',
    'profile_app_language': 'App Language',
    'profile_app_language_subtitle': "Changes the whole app's display language",
    'profile_talk_languages': 'Talk Languages',
    'profile_talk_languages_subtitle': 'Default for Hikaya Talk',
    'profile_i_speak': 'I Speak',
    'profile_they_speak': 'They Speak',
    'profile_your_journeys': 'Your Journeys',
    'profile_no_journeys': 'No journeys yet — plan your first one!',

    // Journey planner input screen
    'plan_title': 'Plan Your Journey',
    'plan_subtitle': 'Craft your perfect adventure',
    'plan_interests_heading': 'What are you interested in?',
    'interest_history': 'History',
    'interest_nature': 'Nature',
    'interest_adventure': 'Adventure',
    'interest_culture': 'Culture',
    'interest_food': 'Food',
    'interest_relaxation': 'Relaxation',
    'plan_budget_heading': 'Budget',
    'plan_transport_heading': 'Transport',
    'transport_car': 'Car',
    'transport_bus': 'Bus',
    'transport_walking': 'Walking',
    'plan_hours_heading': 'How many hours?',
    'plan_generate_button': 'Generate My Journey',
    'plan_pick_interest_error': 'Pick at least one interest',
    'plan_generate_error': 'Failed to generate journey',

    // Hikaya Talk screen
    'talk_title': 'Hikaya Talk',
    'talk_i_speak': 'I Speak',
    'talk_they_speak': 'They Speak',
    'talk_you_said': 'You said',
    'talk_translated': 'Translated',
    'talk_tap_to_speak_hint': 'Tap the mic and start speaking…',
    'talk_translating': 'Translating…',
    'talk_translation_placeholder': 'Translation will appear here',
    'talk_listening': 'Listening…',
    'talk_tap_to_speak': 'Tap to speak',
    'talk_service_busy': 'Translation service is busy — please try again in a moment',

    // Hikaya Hunt — list screen
    'hunt_title': 'Hikaya Hunt',
    'hunt_subtitle': 'Explore challenges around you',
    'hunt_filter_all': 'All',
    'hunt_filter_easy': 'Easy',
    'hunt_filter_medium': 'Medium',
    'hunt_filter_hard': 'Hard',
    'hunt_empty': 'No challenges in this range',
    'hunt_completed': 'Completed',
    'hunt_coins_suffix': 'coins',

    // Hikaya Hunt — detail screen
    'hunt_status_initial': 'Tap "Check My Location" when you arrive',
    'hunt_status_no_permission': 'Location permission needed to unlock this challenge',
    'hunt_status_arrived': "You're here! Take a photo to complete this challenge.",
    'hunt_status_keep_going': 'Keep going —',
    'hunt_status_to_go': 'to go',
    'hunt_status_location_error': 'Error checking location:',
    'hunt_check_location': 'Check My Location',
    'hunt_take_photo_unlock': 'Take Photo & Unlock',
    'hunt_coins_pill': 'Coins',

    // Hikaya Hunt — camera capture
    'hunt_camera_you_are_here': "You're in the right place!",
    'hunt_camera_subtitle': 'Take a photo to unlock the story',
    'hunt_camera_no_photo': 'No photo yet',
    'hunt_camera_retake': 'Retake Photo',
    'hunt_camera_complete': 'Complete Challenge',
    'hunt_camera_retake_dialog_title': 'Take another look?',
    'hunt_camera_retake_dialog_default': "This photo doesn't look like it matches",
    'hunt_camera_wrong_landmark': 'This looks like',
    'hunt_camera_wrong_landmark_not': 'not',
    'hunt_camera_retake_photo_btn': 'Retake Photo',
    'hunt_camera_submit_anyway': 'Submit Anyway',
    'hunt_camera_already_completed': 'Already completed — no duplicate reward given',
    'hunt_camera_submit_failed': 'Failed to submit:',
    'hunt_camera_congrats': 'Congratulations!',
    'hunt_camera_unlocked': 'You unlocked a new story!',
    'hunt_camera_coins_earned': 'Coins Earned',
    'hunt_camera_badge_earned': 'badge earned',
    'hunt_camera_great': 'Great!',

    // Hikaya Hunt — rewards/badges
    'hunt_rewards_title': 'My Rewards',
    'hunt_rewards_not_logged_in': 'Not logged in',
    'hunt_rewards_coins_earned': 'Coins Earned',
    'hunt_rewards_badges_heading': 'Badges',
    'hunt_rewards_no_badges': 'Complete challenges to earn badges',
    'hunt_status_completed': 'Challenge Completed',

    //profile
    'profile_downloaded_journeys': 'Downloaded Journeys',
    'profile_downloaded_journeys_subtitle': 'Saved on this device — available even without a connection',
    'profile_no_downloaded_journeys': 'Nothing downloaded yet — tap "Download Offline" on any journey to save it here',
  };

  static const Map<String, String> ar = {
    // Bottom nav
    'nav_home': 'الرئيسية',
    'nav_journey': 'الرحلة',
    'nav_hunt': 'المطاردة',
    'nav_talk': 'المحادثة',
    'nav_profile': 'الملف الشخصي',

    // Home screen
    'home_greeting': 'صباح الخير',
    'home_headline': 'اكتشف قصص الأردن الخفية',
    'home_plan_journey': 'خطط رحلة',
    'home_hikaya_hunt': 'مطاردة حكاية',
    'home_hikaya_talk': 'حكاية توك',
    'home_continue_journey': 'أكمل رحلتك',
    'home_continue_button': 'متابعة',
    'home_popular_destinations': 'وجهات شائعة',
    'home_view_all': 'عرض الكل',
    'home_no_destinations': 'لا توجد وجهات بعد — شغّل /seed',
    'home_load_error': 'تعذر تحميل الوجهات',
    'unit_stops': 'محطات',
    'unit_hours': 'ساعات',

    // Profile screen
    'profile_title': 'الملف الشخصي',
    'profile_not_logged_in': 'لم يتم تسجيل الدخول',
    'profile_coins': 'العملات',
    'profile_badges': 'الأوسمة',
    'profile_visited': 'تمت زيارتها',
    'profile_view_all_badges': 'عرض جميع الأوسمة',
    'profile_app_language': 'لغة التطبيق',
    'profile_app_language_subtitle': 'تغيّر لغة عرض التطبيق بالكامل',
    'profile_talk_languages': 'لغات المحادثة',
    'profile_talk_languages_subtitle': 'الافتراضي لحكاية توك',
    'profile_i_speak': 'أنا أتحدث',
    'profile_they_speak': 'هم يتحدثون',
    'profile_your_journeys': 'رحلاتك',
    'profile_no_journeys': 'لا توجد رحلات بعد — خطط لأولى رحلاتك!',

    // Journey planner input screen
    'plan_title': 'خطط رحلتك',
    'plan_subtitle': 'صمم مغامرتك المثالية',
    'plan_interests_heading': 'ما الذي يثير اهتمامك؟',
    'interest_history': 'التاريخ',
    'interest_nature': 'الطبيعة',
    'interest_adventure': 'المغامرة',
    'interest_culture': 'الثقافة',
    'interest_food': 'الطعام',
    'interest_relaxation': 'الاسترخاء',
    'plan_budget_heading': 'الميزانية',
    'plan_transport_heading': 'وسيلة التنقل',
    'transport_car': 'سيارة',
    'transport_bus': 'حافلة',
    'transport_walking': 'مشياً',
    'plan_hours_heading': 'كم عدد الساعات؟',
    'plan_generate_button': 'أنشئ رحلتي',
    'plan_pick_interest_error': 'اختر اهتماماً واحداً على الأقل',
    'plan_generate_error': 'فشل إنشاء الرحلة',

    // Hikaya Talk screen
    'talk_title': 'حكاية توك',
    'talk_i_speak': 'أنا أتحدث',
    'talk_they_speak': 'هم يتحدثون',
    'talk_you_said': 'قلتَ',
    'talk_translated': 'الترجمة',
    'talk_tap_to_speak_hint': 'اضغط على الميكروفون وابدأ التحدث…',
    'talk_translating': 'جارٍ الترجمة…',
    'talk_translation_placeholder': 'ستظهر الترجمة هنا',
    'talk_listening': 'يستمع…',
    'talk_tap_to_speak': 'اضغط للتحدث',
    'talk_service_busy': 'خدمة الترجمة مشغولة — يرجى المحاولة مرة أخرى بعد قليل',

    // Hikaya Hunt — list screen
    'hunt_title': 'مطاردة حكاية',
    'hunt_subtitle': 'استكشف التحديات من حولك',
    'hunt_filter_all': 'الكل',
    'hunt_filter_easy': 'سهل',
    'hunt_filter_medium': 'متوسط',
    'hunt_filter_hard': 'صعب',
    'hunt_empty': 'لا توجد تحديات في هذا النطاق',
    'hunt_completed': 'مكتمل',
    'hunt_coins_suffix': 'عملة',

    // Hikaya Hunt — detail screen
    'hunt_status_initial': 'اضغط "تحقق من موقعي" عند وصولك',
    'hunt_status_no_permission': 'إذن الموقع مطلوب لفتح هذا التحدي',
    'hunt_status_arrived': 'لقد وصلت! التقط صورة لإكمال هذا التحدي.',
    'hunt_status_keep_going': 'واصل التقدم —',
    'hunt_status_to_go': 'متبقية',
    'hunt_status_location_error': 'خطأ في التحقق من الموقع:',
    'hunt_check_location': 'تحقق من موقعي',
    'hunt_take_photo_unlock': 'التقط صورة وافتح',
    'hunt_coins_pill': 'عملات',

    // Hikaya Hunt — camera capture
    'hunt_camera_you_are_here': 'أنت في المكان الصحيح!',
    'hunt_camera_subtitle': 'التقط صورة لفتح القصة',
    'hunt_camera_no_photo': 'لا توجد صورة بعد',
    'hunt_camera_retake': 'إعادة التقاط الصورة',
    'hunt_camera_complete': 'إكمال التحدي',
    'hunt_camera_retake_dialog_title': 'ألقِ نظرة أخرى؟',
    'hunt_camera_retake_dialog_default': 'هذه الصورة لا تبدو مطابقة لـ',
    'hunt_camera_wrong_landmark': 'يبدو أن هذه',
    'hunt_camera_wrong_landmark_not': 'وليست',
    'hunt_camera_retake_photo_btn': 'إعادة التقاط الصورة',
    'hunt_camera_submit_anyway': 'إرسال على أي حال',
    'hunt_camera_already_completed': 'مكتمل مسبقاً — لا مكافأة مضاعفة',
    'hunt_camera_submit_failed': 'فشل الإرسال:',
    'hunt_camera_congrats': 'تهانينا!',
    'hunt_camera_unlocked': 'لقد فتحت قصة جديدة!',
    'hunt_camera_coins_earned': 'عملة مكتسبة',
    'hunt_camera_badge_earned': 'وسام مكتسب',
    'hunt_camera_great': 'رائع!',

    // Hikaya Hunt — rewards/badges
    'hunt_rewards_title': 'مكافآتي',
    'hunt_rewards_not_logged_in': 'لم يتم تسجيل الدخول',
    'hunt_rewards_coins_earned': 'عملة مكتسبة',
    'hunt_rewards_badges_heading': 'الأوسمة',
    'hunt_rewards_no_badges': 'أكمل التحديات لكسب الأوسمة',
    'hunt_status_completed': 'التحدي مكتمل',


    //profile
    'profile_downloaded_journeys': 'الرحلات المحمّلة',
    'profile_downloaded_journeys_subtitle': 'محفوظة على هذا الجهاز — متاحة حتى بدون اتصال بالإنترنت',
    'profile_no_downloaded_journeys': 'لا توجد رحلات محمّلة بعد — اضغط على "تنزيل للعمل دون اتصال" في أي رحلة لحفظها هنا',
  };
}